version: '3.8'

services:
  db:
    image: postgres:16
    container_name: myapp-db
    restart: always
    environment:
      POSTGRES_DB: go_avito_db
      POSTGRES_USER: avito_role
      POSTGRES_PASSWORD: 12345678
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U avito_role -d go_avito_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myapp-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: avito_role
      DB_PASSWORD: 12345678
      DB_NAME: go_avito_db
      PORT: 8080
    depends_on:
      db:
        condition: service_healthy
    #volumes:
      # Опционально: для горячей перезагрузки в dev (см. ниже)
      # - .:/app
      # - /app

volumes:
  pgdata: